### ISSUE TITLE
Unit expression editing is broken

### ISSUE THREAD

**Issue by bkolb** [IETS3/iets3.opensource#334] opened 2020-02-24 17:38 UTC
There are several issues when editing expressions with units. 
One example is in this expression:
<img width="80" alt="image" src="https://user-images.githubusercontent.com/355333/75176573-b08a7000-5734-11ea-888f-49efbadf05d4.png">

If the * is replaced with a / the result is this:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/355333/75176645-d6177980-5734-11ea-805f-6b4c36d740f9.png">

**Comment by MLanghammer** [comment] 2020-02-27 17:37
Hi, 
we checked the editing of units.
We were not able to reproduce the error you mentioned. The newly introduced test ChangeUnitOperator  (http://127.0.0.1:63320/node?ref=r%3Aee5b1a89-4907-4bd7-bb79-ba99ef537bd3%28test.ts.expr.os.unitsonly%40tests%29%2F7151854550137080761 ) on branch feature/usability-improvements-unit-editor tests the behavior you mentioned and seems to work.

We, however, investigated the unit editor a bit further and found the following issues:
- when editing the actual unit: pressing enter leads to a new unit-part. There is no easy way to get a newline. In the example, if I go to <no Unit> and press enter another <no Unit>-part will be created.
![grafik](https://user-images.githubusercontent.com/5717036/75469559-84b6f680-598f-11ea-9d89-28438df088d4.png)

- during the first part of the unit pressing "*" has a different behaviour than in the remainding parts. In the first part a multiplication is added in the other parts users need to decide whether to add more parts for the unit of actually having a multiplication.

- errors in the typesystem on the unit are not presented correctly. This will be fixed once the branch datev-staging is merged and will look as follows:
![grafik](https://user-images.githubusercontent.com/5717036/75469705-c182ed80-598f-11ea-8591-54814b56e490.png)

Are these the issues you had in mind when you wrote "several issues" or do you have additional issues in mind?

**Comment by bkolb** [comment] 2020-03-05 07:36
My initial problem was indeed primarily that units got lost on operator changes. That seems to be fixed on master.

**Closed** 2024-08-14 15:03 UTC
Labels: wontfix, AID
