### ISSUE TITLE
Typedef does not implement ITyped

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#138] opened 2018-08-07 13:24 UTC
I am not sure why this is the case. But although a [TypeDef](http://127.0.0.1:63320/node?ref=r%3Ada65683e-ff6f-430d-ab68-32a77df72c93%28org.iets3.core.expr.toplevel.structure%29%2F7740953487936183912) contains child of type **Type** it does not implement the interface [ITyped](http://127.0.0.1:63320/node?ref=r%3A66e07cb4-a4b0-4bf3-a36d-5e9ed1ff1bd3%28org.iets3.core.expr.base.structure%29%2F7071042522334260296).

**Comment by sergej-koscejev** [comment] 2018-08-07 13:51
Why do you need it to implement ITyped?

**Comment by coolya** [comment] 2018-08-09 08:47
I don't think this is a bug. `ITyped` is about more than structure it carries some semantics see the type system rule for how it's type is calculated.

And a `TypeDef` imho is not `ITyped` as for instance a member of a record is. It doesn't *have* a type it *is* a type. A new user defined type.

**Comment by coolya** [comment] 2018-11-22 21:10
Closing as invalid because it's not a bug.

**Closed by coolya** 2018-11-22 21:10 UTC
Labels: bug
