### ISSUE TITLE
Conceptual Problem: Type System tries to ensure that oneOf is always true

### ISSUE THREAD

**Issue by bj2015** [IETS3/iets3.opensource#199] opened 2019-03-14 16:03 UTC
When typechecking the following piece of KernelF code, the typesystem complains that 
"type number is not a subtype of meet[number, number]".

<img width="180" alt="Bildschirmfoto 2019-03-14 um 15 58 09" src="https://user-images.githubusercontent.com/23193107/54367062-0c69ff00-4672-11e9-9670-a45a5be088c9.png">

Interestingly, the following modifications can be typechecked successfully:
<img width="185" alt="Bildschirmfoto 2019-03-14 um 16 00 47" src="https://user-images.githubusercontent.com/23193107/54367238-5b179900-4672-11e9-8175-257fad5b2e50.png">

The error message is caused by the type system rule `typeof_InTarget` which introduces a type variable T and adds constraints to ensure that
1. T is a subtype of all elements of the oneOf
2. y is a subtype of T

The problem is then caused by the fact that `number` is neither a subtype of `number[1,1]` nor of `number[3,3]`

At first I thought that the type system is trying to ensure that the .oneof[]-operation cannot return false. However, this modification does not yield an error:

<img width="189" alt="Bildschirmfoto 2019-03-14 um 16 49 27" src="https://user-images.githubusercontent.com/23193107/54371139-307d0e80-4679-11e9-8312-6668419c0603.png">

Expected Behaviour:
- I do not see any value in trying to ensure that the .oneOf-Operation cannot return false. IMHO, the only thing that should be checked is that the types of its elements are compatible with the type of its receiver.
  - For instance, `"foo".oneof[1,3]` and `3.oneof["foo","bar"]` should both yield an error.
- It is ok that the last example is not automatically flagged as faulty, since this would be really hard to do in the general case.

**Comment by alexanderpann** [comment] 2021-09-21 05:52
Closing this ticket because the expected behaviour seems to be implemented. Feel free to reopen if the problem still exists.

**Closed by alexanderpann** 2021-09-21 05:52 UTC
Labels: bug, kernelf
