### ISSUE TITLE
An NPE could be due to missing coverage

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#18] opened 2016-12-08 14:33 UTC
Note that I am not sure about the origin of this error, this is just a suspicion based on the following:

```
Caused by: com.mbeddr.mpsutil.interpreter.rt.InterpreterRuntimeException: RuntimeException in ||(left[boolean], right[boolean]) on {EXPRESSION REMOVED}:
null
	at org.iets3.core.expr.simpleTypes.plugin.InterpreterExprSimpleTypesInterpeter$9.evaluateEvaluator(Unknown Source)
	at com.mbeddr.mpsutil.interpreter.rt.InterpreterBase.evaluate(InterpreterBase.java:72)
	... 51 more
Caused by: java.lang.NullPointerException
	... 53 more
```

I suspect the piece of code corresponding is:
```
ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x46ff3b3d86cbdcbbL, "org.iets3.core.expr.base.structure.LogicalOrExpression"), true, new TypedChildConstraintImpl(SLinkOperations.findLinkDeclaration(MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x46ff3b3d86c99c15L, 0x46ff3b3d86c99c16L, "left")), SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x6b277d9ad52d416fL, 0xa2091919bd737f50L, 0x670d5e92f854a617L, "org.iets3.core.expr.simpleTypes.structure.BooleanType").getDeclarationNode()))), new TypedChildConstraintImpl(SLinkOperations.findLinkDeclaration(MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x46ff3b3d86c99c15L, 0x46ff3b3d86c99c18L, "right")), SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x6b277d9ad52d416fL, 0xa2091919bd737f50L, 0x670d5e92f854a617L, "org.iets3.core.expr.simpleTypes.structure.BooleanType").getDeclarationNode())))) {
      public Object evaluateEvaluator(SNode node, IContext context, ICoverageAnalyzer coverage) {
        try {
          coverage.visitedEvaluator(this);
          coverage.visitedConcept(this.concept);
          return ((Boolean) castUp(context.getRootInterpreter().evaluate(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x46ff3b3d86c99c15L, 0x46ff3b3d86c99c16L, "left")), context, coverage), Boolean.class)) || ((Boolean) castUp(context.getRootInterpreter().evaluate(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x46ff3b3d86c99c15L, 0x46ff3b3d86c99c18L, "right")), context, coverage), Boolean.class));
        } catch (InterpreterEscapeException ex) {
          throw ex;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("||(left[boolean], right[boolean])", node, ex);
        }
      }
      public EvaluatorInfo getInfo() {
        return new EvaluatorInfo("LogicalOrExpression");
      }

      @Override
      public String toString() {
        return "LogicalOrExpression";
      }
    });
```

It comes from _InterpreterExprSimpleTypesInterpeter_.

**Comment by markusvoelter** [comment] 2016-12-08 14:55
How can I reproduce? NodeURL?

**Comment by ftomassetti** [comment] 2016-12-08 15:00
I will send you the detail over slack

**Comment by alexanderpann** [comment] 2021-09-21 07:16
Closing this ticket because the issue was fixed long ago. The current code also doesn't look the same anymore.

**Closed by alexanderpann** 2021-09-21 07:16 UTC
