### ISSUE TITLE
Transitive dep. resolution fetches packed MPS 2019.1.1

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#247] opened 2019-08-09 17:49 UTC
It looks like after the recent updates on the build scripts and models we have a newly introduced dependency to a fixed version of MPS. 

When resolving iets3.os artifacts transitively a mps 2019.1.1 version is fetched as well.

<img width="1581" alt="image" src="https://user-images.githubusercontent.com/16648247/62798235-1afff980-bade-11e9-84f5-c516459b9a8d.png">

When fetching this dep. trougth iets3.core the artifacts folder is poluted with unrequired content of mps 2019.1.1: see

<img width="296" alt="image" src="https://user-images.githubusercontent.com/16648247/62798456-95307e00-bade-11e9-846e-7bdd8d20a10f.png">

I am not sure if this is intended or maybe required. However it looks odd and the artifacts directy is poluted unnecessary with mps 2019.1.1 artifacts.

**Comment by wsafonov** [comment] 2019-08-12 15:21
I guess the MPS dependency was originally added to the tests publication, but nobody used it and hence this bug hasn't appeared until now.

For your gradle build, you can configure to ignore mps or even the whole tests transitive dependency in the dependencies block like this:

```
    mbeddrPlatformArtifacts("org.iets3:core:$iets3Version") {
        exclude group: 'org.iets3.opensource', module: 'tests'
    }
```

**Comment by arimer** [comment] 2019-08-13 07:17
Thanks for the hint! As a workaround it should work.

**Comment by coolya** [comment] 2019-09-03 13:54
I think the problem is here:

https://github.com/IETS3/iets3.core/blob/master/build.gradle#L115

The tests aren't a `languageLibs` dependency, they are `languageTestLibs` dependency I would say. 

Because we expose all `languageLibs` dependencies in POM which are then used by things that depend on `iets3.core`. But in fact that dependency on the opensource tests isn't required at that time. Its only required when you want to execute the core tests. I think simply moving this dependency into a separate group would already fix the problem. As the dependency on the tests then wouldn't end up in the final POM.

**Comment by wsafonov** [comment] 2019-09-03 17:33
Agree, we just need additionally to resolve the `languageTestLibs` configuration as part of the setup run. I've added a patch for that in core.

**Closed** 2019-09-05 15:43 UTC
