### ISSUE TITLE
Wrong expression binding after inserting ! operator in front of boolean-typed dot expression

### ISSUE THREAD

**Issue by stephaneberle9** [IETS3/iets3.opensource#80] opened 2017-10-27 17:21 UTC
Steps to reproduce:
- Type a 'entity,myBool' kind of expression
- Insert a '!' operator in front of it

Expected result: no errors
Actual result: Error: reference myBool (property) is out of search scope

**Comment by alexanderpann** [comment] 2022-04-28 13:06
Closing because it is not reproducible anymore.

**Closed by alexanderpann** 2022-04-28 13:06 UTC
